from PyQt6.QtWidgets import QApplication, QMainWindow
import sys, lines

list = lines.writ()

def main():
    app = QApplication(sys.argv)
    import proga

    win = QMainWindow()
    win.resize(1600, 800)
    win.setCentralWidget(proga.centralwidget)

    proga.pushButton.clicked.connect(lambda :example(proga.pushButton.text()))
    proga.pushButton_19.clicked.connect(lambda :example(proga.pushButton_19.text()))
    proga.pushButton_20.clicked.connect(lambda :example(proga.pushButton_20.text()))
    proga.pushButton_29.clicked.connect(lambda :example(proga.pushButton_29.text()))
    proga.pushButton_30.clicked.connect(lambda :example(proga.pushButton_30.text()))
    proga.pushButton_31.clicked.connect(lambda :example(proga.pushButton_31.text()))
    proga.pushButton_32.clicked.connect(lambda :example(proga.pushButton_32.text()))
    proga.pushButton_33.clicked.connect(lambda :example(proga.pushButton_33.text()))
    proga.pushButton_35.clicked.connect(lambda :example(proga.pushButton_35.text()))
    proga.pushButton_36.clicked.connect(lambda :example(proga.pushButton_36.text()))
    proga.pushButton_37.clicked.connect(lambda :example(proga.pushButton_37.text()))
    proga.pushButton_38.clicked.connect(lambda :example(proga.pushButton_38.text()))
    proga.pushButton_39.clicked.connect(lambda :example(proga.pushButton_39.text()))
    proga.pushButton_40.clicked.connect(lambda :example(proga.pushButton_40.text()))
    proga.pushButton_41.clicked.connect(lambda :example(proga.pushButton_41.text()))
    proga.pushButton_42.clicked.connect(lambda :example(proga.pushButton_42.text()))
    proga.pushButton_43.clicked.connect(lambda :example(proga.pushButton_43.text()))
    proga.pushButton_45.clicked.connect(lambda :example(proga.pushButton_45.text()))
    proga.pushButton_46.clicked.connect(lambda :example(proga.pushButton_46.text()))
    proga.pushButton_47.clicked.connect(lambda :example(proga.pushButton_47.text()))
    proga.pushButton_48.clicked.connect(lambda :example(proga.pushButton_48.text()))
    proga.pushButton_49.clicked.connect(lambda :example(proga.pushButton_49.text()))
    proga.pushButton_50.clicked.connect(lambda :example(proga.pushButton_50.text()))
    proga.pushButton_51.clicked.connect(lambda :example(proga.pushButton_51.text()))
    proga.pushButton_52.clicked.connect(lambda :example(proga.pushButton_52.text()))
    proga.pushButton_53.clicked.connect(lambda :example(proga.pushButton_53.text()))
    proga.pushButton_55.clicked.connect(lambda :example(proga.pushButton_55.text()))
    proga.pushButton_56.clicked.connect(lambda :example(proga.pushButton_56.text()))
    proga.pushButton_57.clicked.connect(lambda :example(proga.pushButton_57.text()))
    proga.pushButton_58.clicked.connect(lambda :example(proga.pushButton_58.text()))
    proga.pushButton_59.clicked.connect(lambda :example(proga.pushButton_59.text()))
    proga.pushButton_60.clicked.connect(lambda :example(proga.pushButton_60.text()))
    proga.pushButton_61.clicked.connect(lambda :example(proga.pushButton_61.text()))
    proga.pushButton_62.clicked.connect(lambda :example(proga.pushButton_62.text()))
    proga.pushButton_63.clicked.connect(lambda :example(proga.pushButton_63.text()))
    proga.pushButton_65.clicked.connect(lambda :example(proga.pushButton_65.text()))
    proga.pushButton_66.clicked.connect(lambda :example(proga.pushButton_66.text()))
    proga.pushButton_67.clicked.connect(lambda :example(proga.pushButton_67.text()))
    proga.pushButton_68.clicked.connect(lambda :example(proga.pushButton_68.text()))
    proga.pushButton_69.clicked.connect(lambda :example(proga.pushButton_69.text()))
    proga.pushButton_70.clicked.connect(lambda :example(proga.pushButton_70.text()))
    proga.pushButton_24.clicked.connect(lambda :example(proga.pushButton_24.text()))
    proga.pushButton_44.clicked.connect(lambda :example(proga.pushButton_44.text()))
    proga.pushButton_54.clicked.connect(lambda :example(proga.pushButton_54.text()))
    proga.pushButton_34.clicked.connect(lambda :example(proga.pushButton_34.text()))
    proga.pushButton_64.clicked.connect(lambda :example(proga.pushButton_64.text()))
    proga.pushButton_71.clicked.connect(lambda :example(proga.pushButton_71.text()))
    proga.pushButton_72.clicked.connect(lambda :example(proga.pushButton_72.text()))
    proga.pushButton_73.clicked.connect(lambda :example(proga.pushButton_73.text()))
    proga.pushButton_75.clicked.connect(lambda :example(proga.pushButton_75.text()))
    proga.pushButton_76.clicked.connect(lambda :example(proga.pushButton_76.text()))
    proga.pushButton_77.clicked.connect(lambda :example(proga.pushButton_77.text()))
    proga.pushButton_78.clicked.connect(lambda :example(proga.pushButton_78.text()))
    proga.pushButton_80.clicked.connect(lambda :example(proga.pushButton_80.text()))
    proga.pushButton_81.clicked.connect(lambda :example(proga.pushButton_81.text()))
    proga.pushButton_82.clicked.connect(lambda :example(proga.pushButton_82.text()))
    proga.pushButton_83.clicked.connect(lambda :example(proga.pushButton_83.text()))
    proga.pushButton_84.clicked.connect(lambda :example(proga.pushButton_84.text()))
    proga.pushButton_85.clicked.connect(lambda :example(proga.pushButton_85.text()))
    proga.pushButton_86.clicked.connect(lambda :example(proga.pushButton_86.text()))
    proga.pushButton_87.clicked.connect(lambda :example(proga.pushButton_87.text()))
    proga.pushButton_89.clicked.connect(lambda :example(proga.pushButton_89.text()))
    proga.pushButton_90.clicked.connect(lambda :example(proga.pushButton_90.text()))
    proga.pushButton_91.clicked.connect(lambda :example(proga.pushButton_91.text()))
    proga.pushButton_92.clicked.connect(lambda :example(proga.pushButton_92.text()))
    proga.pushButton_93.clicked.connect(lambda :example(proga.pushButton_93.text()))
    proga.pushButton_94.clicked.connect(lambda :example(proga.pushButton_94.text()))
    proga.pushButton_95.clicked.connect(lambda :example(proga.pushButton_95.text()))
    proga.pushButton_96.clicked.connect(lambda :example(proga.pushButton_96.text()))
    proga.pushButton_98.clicked.connect(lambda :example(proga.pushButton_98.text()))
    proga.pushButton_99.clicked.connect(lambda :example(proga.pushButton_99.text()))
    proga.pushButton_101.clicked.connect(lambda :example(proga.pushButton_101.text()))
    proga.pushButton_102.clicked.connect(lambda :example(proga.pushButton_102.text()))
    proga.pushButton_103.clicked.connect(lambda :example(proga.pushButton_103.text()))
    proga.pushButton_104.clicked.connect(lambda :example(proga.pushButton_104.text()))
    proga.pushButton_106.clicked.connect(lambda :example(proga.pushButton_106.text()))
    proga.pushButton_108.clicked.connect(lambda :example(proga.pushButton_108.text()))
    proga.pushButton_109.clicked.connect(lambda :example(proga.pushButton_109.text()))
    proga.pushButton_110.clicked.connect(lambda :example(proga.pushButton_110.text()))
    proga.pushButton_111.clicked.connect(lambda :example(proga.pushButton_111.text()))
    proga.pushButton_112.clicked.connect(lambda :example(proga.pushButton_112.text()))
    proga.pushButton_113.clicked.connect(lambda :example(proga.pushButton_113.text()))
    proga.pushButton_114.clicked.connect(lambda :example(proga.pushButton_114.text()))
    proga.pushButton_116.clicked.connect(lambda :example(proga.pushButton_116.text()))
    proga.pushButton_117.clicked.connect(lambda :example(proga.pushButton_117.text()))
    proga.pushButton_121.clicked.connect(lambda :example(proga.pushButton_121.text()))
    proga.pushButton_123.clicked.connect(lambda :example(proga.pushButton_123.text()))
    proga.pushButton_125.clicked.connect(lambda :example(proga.pushButton_125.text()))
    proga.pushButton_126.clicked.connect(lambda :example(proga.pushButton_126.text()))
    proga.pushButton_18.clicked.connect(lambda :example(proga.pushButton_18.text()))
    proga.pushButton_8.clicked.connect(lambda :example(proga.pushButton_8.text()))
    proga.pushButton_15.clicked.connect(lambda :example(proga.pushButton_15.text()))
    proga.pushButton_4.clicked.connect(lambda :example(proga.pushButton_4.text()))
    proga.pushButton_3.clicked.connect(lambda :example(proga.pushButton_3.text()))
    proga.pushButton_16.clicked.connect(lambda :example(proga.pushButton_16.text()))
    proga.pushButton_11.clicked.connect(lambda :example(proga.pushButton_11.text()))
    proga.pushButton_9.clicked.connect(lambda :example(proga.pushButton_9.text()))
    proga.pushButton_13.clicked.connect(lambda :example(proga.pushButton_13.text()))
    proga.pushButton_2.clicked.connect(lambda :example(proga.pushButton_2.text()))
    proga.pushButton_17.clicked.connect(lambda :example(proga.pushButton_17.text()))
    proga.pushButton_5.clicked.connect(lambda :example(proga.pushButton_5.text()))
    proga.pushButton_6.clicked.connect(lambda :example(proga.pushButton_6.text()))
    proga.pushButton_12.clicked.connect(lambda :example(proga.pushButton_12.text()))
    proga.pushButton_21.clicked.connect(lambda :example(proga.pushButton_21.text()))
    proga.pushButton_7.clicked.connect(lambda :example(proga.pushButton_7.text()))
    proga.pushButton_25.clicked.connect(lambda :example(proga.pushButton_25.text()))
    proga.pushButton_10.clicked.connect(lambda :example(proga.pushButton_10.text()))




    win.show()
    sys.exit(app.exec())


def example(info):
    import proga
    
    info = info.split(' ')
    proga.label_27.setText(str(list[int(info[1])-1]))

main()
